[agent]
    interval = "20s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    debug = true
    quiet = false
    hostname = ""
    omit_hostname = false

#############################################################
#                   OUTPUT PLUGINS                          #
#############################################################
[[outputs.influxdb_v2]]

    urls = [ "http://influxdb:8086" ]
    token = "${INFLUX_TOKEN}"
    organization = "${DOCKER_INFLUXDB_INIT_ORG}"
    bucket = "${DOCKER_INFLUXDB_INIT_BUCKET}"

    timeout = "5s"


##################################################################
#                   INPUT PLUGINS                                #
##################################################################

[[inputs.mqtt_consumer]]

    servers = [ "ssl://mosquitto:8883" ]

    # Topics to subscribe to:
    topics = [
        "test/#"
    ]

    # Connection timeout
    connection_timeout = "30s"

    username = "${TG_MOSQUITTO_USERNAME}"
    password = "${TG_MOSQUITTO_PASSWORD}"

    ## Use TLS but skip chain & host verification
    # Use Certificates if `require_certificate true` in `mosquitto.conf` file
    tls_ca = "/etc/telegraf/ca-chain.cert.pem"
    tls_cert = "/etc/telegraf/mqtt-client.cert.pem"
    tls_key = "/etc/telegraf/mqtt-client.key.pem"
    ## Use TLS but skip chain & host verification
    insecure_skip_verify = true

    data_format = "json"

[[inputs.ping]]
  # urls to ping
  urls = ["192.168.88.1"] # required
  # number of pings to send (ping -c <COUNT>)
  count = 1 # required
  # interval, in s, at which to ping. 0 == default (ping -i <PING_INTERVAL>)
  ping_interval = 0.0
  # ping timeout, in s. 0 == no timeout (ping -t <TIMEOUT>)
  timeout = 0.0
  # interface to send ping from (ping -I <INTERFACE>)
  interface = ""